- hosts: localhost

  vars_files:
    - default.config.yml

  vars:
    homebrew_installed_packages:
      - pv
      - neovim
      - tmux
      - neofetch
      - tree
      - romkatv/powerlevel10k/powerlevel10k
      - bpytop
      - fzf
      - ripgrep
      - weechat

    homebrew_uninstalled_packages: []


    homebrew_cask_apps:
      - firefox
      - google-chrome
      - alfred
      - discord
      - reaper
      - visual-studio-code
      - kitty
      - amethyst
      - google-drive
      - nextcloud
      - notion
      - signal
      - the-unarchiver

    homebrew_cask_uninstalled_apps: []

    dockitems_remove:
      - Launchpad
      - TV
      - 'App Store'
      - News
      - Contacts
      - Maps
      - 'System Preferences'
      - Music
      - Terminal
      - Safari
      - Photos
      - Calendar
      - Reminders

    dockitems_persist:
      - name: Reaper
        path: "/Applications/REAPER-ARM.app"
      - name: Kitty
        path: "/Applications/Kitty.app"
      - name: Discord
        path: "/Applications/Discord.app"
      - name: Firefox
        path: "/Applications/Firefox.app"
      - name: Notion
        path: "/Applications/Notion.app"

  roles:
    - role: geerlingguy.mac.homebrew

    - role: geerlingguy.mac.dock
      when: configure_dock

    - role: vim-plug

    - role: dotfiles
      when: configure_dotfiles
