- name: Install vim-plug 
  ansible.builtin.shell:
    cmd: curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  when: from_scratch == true

- name: Copy init.vim
  ansible.builtin.copy:
    src: files/init.vim
    dest: ~/.config/nvim/init.vim
    mode: 0755
    owner: vik
    group: staff
  when: from_scratch == true
